stages:
  preprocess:
    cmd: python preprocess.py
    deps:
      - data/train_titanic.csv
      - preprocess.py
    outs:
      - data/train.csv
      - data/test.csv

  train:
    cmd: python train.py
    deps:
      - data/train.csv
      - train.py
    outs:
      - models/model.pkl

  validate:
    cmd: python validate.py
    deps:
      - models/model.pkl
      - data/test.csv
      - validate.py
    metrics:
      - metrics.json:
          cache: false
    plots:
      - confusion_matrix.png:
          cache: false
